config/routes.rb
Rails.application.routes.draw do
  root "posts#index"

  get "/login", to: "login#new"
  post "/login", to: "login#create"
  delete "/logout", to: "login#destroy"


  resources :posts, except: :index do
    resources :purchases, only: [:create], module: :posts
  end

  namespace :stripe do
    namespace :checkout do
      resources :successes, only: [:show]
      resources :cancellations, only: [:show]
      resources :webhooks, only: [:create]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :author, class_name: "User"

  validates :body, :post_id, :author_id, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: "User"
  has_many :comments, dependent: :destroy

  validates :title, :body, :author_id, presence: true

  scope :ordered, -> { order(updated_at: :desc) }

  def attribution
    "by #{author.name}"
  end
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :user, presence: true
  validates :post, presence: true

  scope :post_paid, ->(post) { order(created_at: :desc).where(post: post, paid: true) }

  def paid!
    self.paid = true
    save
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :posts, foreign_key: "author_id", dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :purchases

  validates :first_name, presence: true

  def name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def login_required
    redirect_to(login_path, alert: t("login_required")) unless current_user
  end

  def user_not_authorized
    redirect_to(root_path, alert: t("unauthorized"))
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  before_action :only_for_anonymous, except: :destroy

  def new; end

  def create
    user = User.find_by(username: params[:username])
    if user&.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: t(".success")
    else
      redirect_to login_path, alert: t(".error")
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to root_path, notice: t(".success")
  end

  private

  def only_for_anonymous
    redirect_to root_path if session[:user_id]
  end
end

app/controllers/posts/purchases_controller.rb
module Posts
  class PurchasesController < ApplicationController
    before_action :login_required

    def create
      result = StartPurchaseService.call(current_user,
        post_id: params[:post_id],
        success_url: stripe_checkout_success_url(params[:post_id]),
        cancel_url: stripe_checkout_cancellation_url(params[:post_id])
      )

      if result.ok?
        render json: { sessionId: result.session_id }
      else
        redirect_to post_url(params[:post_id]), notice: t(".purchase_error")
      end
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :login_required, except: [:index, :show]
  before_action :fetch_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = policy_scope(Post).ordered
  end

  def show; end

  def new
    @post = Post.new
    authorize @post, :create?
  end

  def create
    @post = Post.new(permitted_params)
    @post.author = current_user
    authorize @post, :create?

    if @post.save
      redirect_to @post, notice: t(".success")
    else
      render :new
    end
  end

  def edit
    authorize @post, :update?
  end

  def update
    authorize @post, :update?
    if @post.update(permitted_params)
      redirect_to @post, notice: t(".success")
    else
      render :edit
    end
  end

  def destroy
    authorize @post, :update?
    if @post.destroy
      redirect_to root_path, notice: t(".success")
    else
      redirect_to root_path, alert: t(".error")
    end
  end

  private

  def fetch_post
    @post = Post.find(params[:id])
  end

  def permitted_params
    params.require(:post).permit(
      :title,
      :body,
    )
  end
end

app/controllers/stripe/checkout/cancellations_controller.rb
module Stripe
  module Checkout
    class CancellationsController < ApplicationController
      before_action :login_required

      def show
        redirect_to post_url(params[:id]), alert: t(".cancelled")
      end
    end
  end
end

app/controllers/stripe/checkout/successes_controller.rb
module Stripe
  module Checkout
    class SuccessesController < ApplicationController
      before_action :login_required

      def show
        redirect_to post_url(params[:id]), notice: t(".successful")
      end
    end
  end
end

app/controllers/stripe/checkout/webhooks_controller.rb
module Stripe
  module Checkout
    class WebhooksController < ApplicationController
      skip_before_action :verify_authenticity_token

      def create
        result = ProcessPaymentService.call(request.raw_post,
          secret: Rails.application.secrets.stripe_secret_webhook_key,
          signature: request.headers["HTTP_STRIPE_SIGNATURE"]
        )

        if result
          head :ok
        else
          head :bad_request
        end
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title(prefix = nil)
    key = "#{controller_path.tr("/", ".")}.#{action_name}.page_title"
    title = t(
      key,
      prefix: prefix,
      site_name: t("site_name"),
      default: :site_name
    )

    content_for(:page_title, title)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:page_title) || t("site_name") %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class="navbar">
      <div class="navbar__container">
        <div class="navbar__left">
          <%= link_to(root_path) do %>
            <%= image_tag "logo.svg", width: 34 %>
          <% end %>
        </div>
        <div class="navbar__right">
          <% if current_user %>
            <%= link_to(t("logout.text"), logout_path, data: { method: :delete }, class: "form__button form__button--danger") %>
          <% else %>
            <%= link_to(t("login.text"), login_path, class: "form__button form__button--primary") %>
          <% end %>
        </div>
      </div>
    </div>

    <div class="container">
      <% flash.each do |name, msg| %>
        <div class="notification notification__<%= name %>">
          <%= msg %>
        </div>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/login/new.html.erb
<%= form_with(url: login_path, method: :post, local: true) do |form| %>
<div class="form__field">
  <%= form.text_field :username, class: "form__control", required: true %>
  <span class="form__highlight"></span>
  <span class="form__bar"></span>
  <%= form.label :username, class: "form__label" %>
</div>
<div class="form__field">
  <%= form.password_field :password, class: "form__control", required: true %>
  <span class="form__highlight"></span>
  <span class="form__bar"></span>
  <%= form.label :password, class: "form__label" %>
</div>
<div class="form__actions">
  <%= form.submit t("login.text"), class: "form__button form__button--primary" %>
  <%= link_to t("cancel.text"), root_path, class: "form__button form_button--secondary" %>
</div>
<% end %>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <div class="form__field">
    <%= form.text_field :title, class: "form__control", required: true %>
    <span class="form__highlight"></span>
    <span class="form__bar"></span>
    <%= form.label :title, class: "form__label" %>
  </div>
  <div class="form__field">
    <%= form.text_area :body, class: "form__control", rows: 20, required: true %>
    <span class="form__highlight"></span>
    <span class="form__bar"></span>
    <%= form.label :body, class: "form__label" %>
  </div>
  <div class="form__actions">
    <%= form.submit class: "form__button form__button--primary" %>
    <%= link_to t("cancel.text"), root_path, class: "form__button form_button--secondary" %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="post <%= "post--border" if action_name == "index" %>">
  <div class="post__meta">
    <span class="post__meta-author"><%= post.author.name %></span>
    <span class="post__meta-published"><%= l(post.created_at.to_date, format: :short) %></span>
    <span class="post__meta-divider"></span>
    <span class="post__meta-comments"><%= pluralize(post.comments.count, "Comment") %></span>
  </div>
  <h2 class="post__title">
    <% if local_assigns[:link_title].presence %>
      <%= link_to(post.title, post) %>
    <% else %>
      <%= post.title %>
    <% end %>
  </h2>
  <div class="post__body">
    <% if local_assigns[:expand_body].presence %>
      <% if policy(post).read? %>
        <%= sanitize(post.body) %>
      <% else %>
        <%= sanitize(post.body.truncate(1500, omission: "...")) %>
        <%= render partial: "post_purchase", locals: { post: post } %>
      <% end%>
    <% else %>
      <%= sanitize(post.body.truncate(200, omission: "...")) %>
      <%= link_to "Read more...", post, class: "post__continue" %>
    <% end %>
  </div>
</div>

app/views/posts/_post_purchase.html.erb
<div class="post__purchase-notification">
  <h1>Payment</h1>
  <p><%= t("purchase.prompt") %></p>
  <% if current_user %>
    <%= link_to(t("purchase.button"), "#", id: "purchase", class: "form__button form__button--primary") %>
    <script src="https://js.stripe.com/v3/"></script>
    <script>
      const stripe = Stripe('<%= Rails.application.secrets.stripe_publishable_key %>')

      const handleResult = result => {
        if (result.error) {
          let displayError = document.querySelector('#purchase-error')
          let customerMessage =
            'We are sorry but purchasing error occurred. Please contact support.'
          displayError.textContent = customerMessage
          console.error(result.error.message) // log with bug tracking service
        }
      }

      const checkout = data => {
        stripe
          .redirectToCheckout({ sessionId: data.sessionId })
          .then(handleResult)
      }

      const getCSRF = () => {
        const csrfElement = document.querySelector('meta[name="csrf-token"]')
        let csrfToken
        if (csrfElement !== null) {
          csrfToken = csrfElement.content
        }
        return csrfToken
      }

      const checkoutListener = event => {
        event.preventDefault()

        const csrfToken = getCSRF()

        const purchaseSessionUrl = '<%= post_purchases_url(post) %>'
        const purchaseSessionArguments = {
          method: 'POST',
          headers: { 'X-CSRF-Token': csrfToken }
        }

        fetch(purchaseSessionUrl, purchaseSessionArguments)
          .then(result => { return result.json() })
          .then(checkout)
      }

      document.addEventListener('DOMContentLoaded', () => {
        document.querySelector('#purchase').addEventListener('click', checkoutListener)
      })
    </script>
  <% else %>
    <%= link_to(t("login.text"), login_path, class: "form__button form__button--primary") %>
  <% end %>
</div>

app/views/posts/edit.html.erb
<%= render partial: "form", locals: { post: @post } %>

app/views/posts/index.html.erb
<% if policy(:post).create? %>
  <%= link_to(t("new.text", resource: "Post"), new_post_path, class: "form__button form__button--primary") %>
<% end %>


<%= render @posts, link_title: true %>

app/views/posts/new.html.erb
<%= render partial: "form", locals: { post: @post } %>

app/views/posts/show.html.erb
<% page_title(@post.title) %>

<% if policy(@post).update? %>
  <div class="form__actions">
    <%= link_to(t("edit.text"), edit_post_path(@post), class: "form__button form__button--primary") %>
    <%= link_to(t("delete.text"), @post, data: { method: :delete, confirm: t("delete.confirm") }, class: "form__button form__button--danger") %>
  </div>
<% end %>

<%= render @post, expand_body: true %>